trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install pytest pytest-cov pytest-azurepipelines
  displayName: 'Install dependencies and coverage tools'

- script: |
    pytest --cov=. --cov-report=xml
  displayName: 'Run tests and generate coverage report'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sq20251' # Replace with your service connection name
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'pytest-github-actions-example'
    cliProjectName: 'pytest-github-actions-example'
    cliSources: '.'
    extraProperties: |
      sonar.python.coverage.reportPaths=coverage.xml

- task: SonarQubeAnalyze@5
  displayName: 'Run SonarQube Analysis'

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'